### ISSUE TITLE
Brother, I am Pinned Here!

### ISSUE THREAD

**Issue by ZeDocktor** [multimokia/MAS-Submods#1]
Greetings, I am completely new to modifying/adding modifications to the MAS mod, however I would like to start by adding these sub-mods. However, as I am new and in truth probably too cautious/afraid in this, I do not know how exactly do go about doing this. 

From what I can observe from the "Night Music" and "Auto Hair Change" mods that they area simple copy and paste into a specific file within the mod folders, but to what files I am unaware. As such I request some assistance from those of you who know more than me on this topic, on how and where to apply these mods to my computer.

I thank you in advance for your assistance.

**Comment by multimokia** [comment]
I'd personally just keep a submods folder within your `game/` folder and put the `.rpy` files in there. Next time you launch MAS it'll be compiled and loaded up. They don't modify other game files so they can be uninstalled with ease.

**Comment by ZeDocktor** [comment]
Thank you, Loyal Citizen. I shall now close this thread but leave it here for future adventurers to find!
