### ISSUE TITLE
Updated EL to 1.0.1 but still getting hangman bug

### ISSUE THREAD

**Issue by Abc2557** [multimokia/MAS-Submods#18]
I updated English Localization to version 1.0.1, but I'm still getting the "expected string or buffer" bug when I play hangman. I even tried deleting the EL folder in Submods, and I still get the error

**Comment by multimokia** [comment]
Wait so it's _uninstalled_ and you still get the issue?


Also I can't seem to replicate this on my end. Making a fresh MAS install (no other code and/or submods installed) and Hangman seems to work perfectly fine. Is there a second version installed? (Which version shows in the settings menu)?

**Comment by Abc2557** [comment]
First I tried with 1.0.0, got the bug. Uninstalled, still go the bug. Redownloaded as 1.0.1, still got the bug. I currently have 1.0.1 installed, according to the Submods Settings menu

**Comment by Abc2557** [comment]
Both uninstalling and downloading the 1.0.1 update don’t appear to have changed anything other than what appears in the Submods Settings menu

**Comment by multimokia** [comment]
Say goodbye and send `mas_log.txt` please

**Comment by Abc2557** [comment]
[mas_log.txt](https://github.com/multimokia/MAS-Submods/files/4995652/mas_log.txt)

**Comment by multimokia** [comment]
Looks like you still have the old one installed. Same goes for auto atmos change. This means that the code from 1.0.0 is still active and breaking hangman for you.

You should always paste everything in the same place you did for the first install and replace all files. That way it makes sure everything is updated.

**Comment by Abc2557** [comment]
Mm, alright. I'll try to find the old ones and uninstall them. Thanks for your help

**Comment by Abc2557** [comment]
I was able to find the old auto atmos install and deleted it fine. For English localization, though, I couldn't find any second install or old install anywhere, so I just deleted the folder in Submods and redownloaded it, then opened MAS. Hangman still doesn't work properly, and I can't seem to find any old/second installs of the submod anywhere

**Comment by multimokia** [comment]
You sure there's not a copy of it in `/game` or any other folder?

**Comment by Abc2557** [comment]
Oh.. apparently there's an English locale settings rpyc file in game. Dunno how it got there, but I'll try closing MAS, deleting it, and reopening MAS. Sorry I didn't think to check the game folder

**Comment by Abc2557** [comment]
It works now! Thanks for the help and sorry to bother you!

**Comment by multimokia** [comment]
No problem!
