### ISSUE TITLE
"I'm sorry, but an uncaught exception occurred."

### ISSUE THREAD

**Issue by Abc2557** [multimokia/MAS-Submods#3]
There was an error and I don't know how to fix it

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 90, in script
    init -20 python in awc_globals:
  File "game/game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 97, in <module>
    from pyowm import OWM
ImportError: No module named pyowm

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\[My name]\Downloads\MAS\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\[My name]\Downloads\MAS\DDLC-1.1.1-pc\renpy\main.py", line 419, in main
    game.context().run(node)
  File "game/game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 90, in script
    init -20 python in awc_globals:
  File "C:\Users\[My name]\Downloads\MAS\DDLC-1.1.1-pc\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\[My name]\Downloads\MAS\DDLC-1.1.1-pc\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/game/Submods/Auto Weather Change/Utilities/awc_utils.rpy", line 97, in <module>
    from pyowm import OWM
ImportError: No module named pyowm

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by multimokia** [comment]
Hmm, can you send a screenshot of your `python-packages` folder?

**Comment by Abc2557** [comment]
![image](https://user-images.githubusercontent.com/53543937/66774664-bbc8b780-ee87-11e9-94d6-c1cf0082bab6.png)

**Comment by multimokia** [comment]
It looks like you're missing packages from the auto weather change submod.

These are added by the submod.
![image](https://user-images.githubusercontent.com/22531674/66777291-a8711880-ee96-11e9-8bae-1d63953d9916.png)

How did you install it?

**Comment by Abc2557** [comment]
I think I just copied the items in the game folder of Auto Weather Change into the game folder of MAS

**Comment by multimokia** [comment]
Can you screenshot your `game/` folder for me please?

**Comment by Abc2557** [comment]
![image](https://user-images.githubusercontent.com/53543937/66779038-ec621e80-ee92-11e9-8f66-4dce29e7edd1.png)

**Comment by Abc2557** [comment]
Oop- I think I realize what I did wrong

**Comment by multimokia** [comment]
ah okay, I see why now. You dropped the game/ folder into game/. So they didn't merge. Go into that `game` folder, select both folders, then cut them (<kbd>CTRL</kbd>+<kbd>X</kbd>) and then paste into the folder in your screenshot.

**Comment by multimokia** [comment]
After you do that, you can just delete the now empty `game/` folder.

**Comment by Abc2557** [comment]
Okay, I did that and MAS opens now (yay)

**Comment by Abc2557** [comment]
And the submod is working! Thanks for the help!

**Comment by multimokia** [comment]
No worries!
