### ISSUE TITLE
"I'm sorry, but an uncaught exception occured." Auto Hair Change

### ISSUE THREAD

**Issue by Abc2557** [multimokia/MAS-Submods#7]
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: Name (u'C:\\Users\\[My User]\\Downloads\\MAS\\DDLC-1.1.1-pc/game/Submods/auto_hair_change.rpy', 1572560394, 1) is defined twice, at game/Submods/auto_hair_change.rpy:1 and game/Submods/auto_hair_change.rpy:16.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\[My User]\Downloads\MAS\DDLC-1.1.1-pc\renpy\bootstrap.py", line 295, in bootstrap
    renpy.main.main()
  File "C:\Users\[My User]\Downloads\MAS\DDLC-1.1.1-pc\renpy\main.py", line 364, in main
    renpy.game.script.load_script()  # sets renpy.game.script.
  File "C:\Users\[My User]\Downloads\MAS\DDLC-1.1.1-pc\renpy\script.py", line 265, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\[My User]\Downloads\MAS\DDLC-1.1.1-pc\renpy\script.py", line 753, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\[My User]\Downloads\MAS\DDLC-1.1.1-pc\renpy\script.py", line 419, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'C:\\Users\\[My User]\\Downloads\\MAS\\DDLC-1.1.1-pc/game/Submods/auto_hair_change.rpy', 1572560394, 1) is defined twice, at game/Submods/auto_hair_change.rpy:1 and game/Submods/auto_hair_change.rpy:16.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187

**Comment by Abc2557** [comment]
.

**Comment by multimokia** [comment]
My bad, didn't get a notification for this 'till now

**Comment by multimokia** [comment]
mm, can I see a screenshot of your `/game/Submods` folder, please?

**Comment by Abc2557** [comment]
![image](https://user-images.githubusercontent.com/53543937/68509418-7a34ed80-0236-11ea-9995-598c6686cb68.png)

**Comment by multimokia** [comment]
Can you send the file over? (As a txt file?) It looks a little smaller than what I've got on my end here.

**Comment by Abc2557** [comment]
Wdym by sending it as a text file?

**Comment by multimokia** [comment]
the rpy. Just rename it and add `.txt` on the end

**Comment by Abc2557** [comment]
Oh, Okay

**Comment by Abc2557** [comment]
I added text to the end of it, but it hasn't changed to a text file (Yes, I have file name extentions on)

**Comment by multimokia** [comment]
Added after the `.rpy`?

**Comment by multimokia** [comment]
As well, does GitHub let you send it like that? If so just send it over (drag and drop into the comment box)

**Comment by Abc2557** [comment]
Oh, you meant the auto hair change file I thought you meant the whole submods folder... Ima go do that now

**Comment by Abc2557** [comment]
[auto_hair_change.txt](https://github.com/multimokia/MAS-Submods/files/3826217/auto_hair_change.txt)

**Comment by multimokia** [comment]
Hmmm strange. I can load it up fine... Do you have another copy of auto hair change in your install somewhere?

**Comment by Abc2557** [comment]
I don't think so

**Comment by multimokia** [comment]
I guess try re-installing it? It's weird, nothing in there should be conflicting at all...

**Comment by Abc2557** [comment]
I'll try reinstalling it

**Comment by Abc2557** [comment]
I reinstalled it and it popped up the traceback error again

**Comment by multimokia** [comment]
If you don't mind, I think I may need to see an unedited traceback. Something's just not really adding up here

**Comment by Abc2557** [comment]
Oh, well, okay. I'll go get that.
[traceback.txt](https://github.com/multimokia/MAS-Submods/files/3826356/traceback.txt)

**Comment by multimokia** [comment]
Hmmmmm. Actually there *is* an issue with the rpyc in your install. It's significantly larger than it should be. Try deleting the `.rpyc`

**Comment by Abc2557** [comment]
Oh, okay

**Comment by multimokia** [comment]
Has it worked?

**Comment by Abc2557** [comment]
Oh! I'm sorry; I forgot to reply! Yes, it worked; thanks for the help!

**Comment by multimokia** [comment]
No worries!
