### ISSUE TITLE
Question about Auto Weather mod: changing location?

### ISSUE THREAD

**Issue by lunulae** [multimokia/MAS-Submods#8]
I'm going to be traveling for some time in the near future, I was wondering if there was currently a way to get Monika to ask me for my location again. Would a clean reinstall of the weather mod work?

**Comment by multimokia** [comment]
This is not a problem at all:

Simply go to `Repeat conversation > You > [player]'s location`

**Comment by lunulae** [comment]
Oh, that's much simpler than I thought! Thank you so much!
