### ISSUE TITLE
RE: Nightmusic

### ISSUE THREAD

**Issue by ghost** [multimokia/MAS-Submods#9]
Hey there, thank you in advance for your assistance and for making these submods!

I am running MAS version 0.10.7 (current) and have been unable to get Nightmusic working on Win7, Win8.1 and Ubuntu 18.04.4.  The submod seems to have been installed correctly, as I get an option to select 'Nightmusic' in the music selection panel as well as the playlist option button, but when I click 'Nightmusic' nothing plays from that folder.  If there is already music playing, the same music continues - and if there is no music playing then nothing plays.  I don't get any error messages, it's simply that nothing happens.  I tried waiting for nightfall with no music playing to see if Monika would start playing music from that folder, but again nothing happens.  

Any suggestions would be greatly appreciated, thank you for your time!

**Comment by multimokia** [comment]
Hey there!
Firstly, I assume you're running the latest Nightmusic, in which case, can I see a screenshot of your `nightmusic` folder? I know you mentioned them being mp3's. Additionally, can I see the `genre` field of the song(s) in there? I get the feeling that may be our cause.

**Comment by ghost** [comment]
Thanks for your prompt reply!
Yup, I am using the latest Nightmusic.  Here is a screenshot of my nightmusic folder:

[Untitled 1.docx](https://github.com/multimokia/MAS-Submods/files/4215642/Untitled.1.docx)

Here are the genre fields for each of the songs:

[Untitled 2.docx](https://github.com/multimokia/MAS-Submods/files/4215661/Untitled.2.docx)

**Comment by multimokia** [comment]
Ah okay, I see the issue. Change the genre to be empty (just delete the text there) As of the latest nightmusic, the `genre` field is used for conditionals, things which fail to evaluate (these will) are just assumed to have failed the condition, so they're not picked.

**Comment by ghost** [comment]
Ok, I cleared the genre field and Nightmusic is now working perfectly on Win7 and Win8.1, however it isn't quite working on Ubuntu.  I do get the dialogue where she tells me she's going to put something on now that I cleared the genre field, but no music plays.  When I click on the Nightmusic button in the music selection menu, no music plays either.

**Comment by multimokia** [comment]
Noted, I think I'll need to experiment with linux to read audio metadata

**Comment by ghost** [comment]
Thank you!

**Comment by multimokia** [comment]
Alrighty, it's been ages since I've had the full time to go into this. But I've gotten myself an Ubuntu vm and have been experimenting.

I've found the source of the issue, turns out it's not an issue in the submod itself, but actually a renpy issue. I've also managed to fix this via overriding some of renpy's core functions to make this work as it does on Windows.

If all works well on the Windows OS, I'll try to push these changes to upstream MAS so Nightmusic works just fine on Linux PCs (along with other renpy things) without needing to update the submod.

**Comment by multimokia** [comment]
Given that we'll be waiting for a while for the renpy repository to consider the pull request (which is the hold for the upstream MAS one), I'll make some overrides on the submod itself in the meantime and I'll remove it once that's merged.

**Comment by multimokia** [comment]
Try using [this version](https://github.com/multimokia/MAS-Submods/releases/tag/NM_2.1.4) Of NightMusic. It should fix the issues you're having both here and in #10

**Comment by ghost** [comment]
Awesome, thank you so much!  Looks like everything is working as expected.

**Comment by multimokia** [comment]
Great!

**Comment by multimokia** [comment]
Hey @d3adpan, just wondering if you had Discord or something. I've got another submod in the works which I can get working on Windows, but I'm having trouble looking for some equivalent commands for Linux. Seems to be almost non-existent. Would *really* love to get this one especially working cross-platform. If you do, think you could add me? `multimokia#0007`

**Comment by ghost** [comment]
Hey @multimokia I think I still have one on the Windows tablet, which I unfortunately left home.  I'll be happy to help, I should be home by Thursday the latest if that works?

**Comment by multimokia** [comment]
Cool, sounds great. Feel free to send a friend request and we'll go from there!

**Comment by ghost** [comment]
Sweet, you got it.  Chat soon!
